//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.225
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smacop2 {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class mensajes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal mensajes() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("smacop2.mensajes", typeof(mensajes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Existen campos sin diligenciar, por favor verifique....
        /// </summary>
        internal static string Msg01 {
            get {
                return ResourceManager.GetString("Msg01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro que desea Eliminar el presente registro?.
        /// </summary>
        internal static string Msg02 {
            get {
                return ResourceManager.GetString("Msg02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existen Registros.
        /// </summary>
        internal static string Msg03 {
            get {
                return ResourceManager.GetString("Msg03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambios Aplicados.
        /// </summary>
        internal static string Msjconf {
            get {
                return ResourceManager.GetString("Msjconf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No pudo proceder con la operación, comuniquese con el proveedor....
        /// </summary>
        internal static string MsjProc0 {
            get {
                return ResourceManager.GetString("MsjProc0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Registro fue Grabado.
        /// </summary>
        internal static string MsjProc1 {
            get {
                return ResourceManager.GetString("MsjProc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Registro fue Actualizado.
        /// </summary>
        internal static string MsjProc2 {
            get {
                return ResourceManager.GetString("MsjProc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Registro Fue Eliminado !.
        /// </summary>
        internal static string MsjProc3 {
            get {
                return ResourceManager.GetString("MsjProc3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Registro ya existe!!!.
        /// </summary>
        internal static string MsjProc4 {
            get {
                return ResourceManager.GetString("MsjProc4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Desea Actualizarlo?.
        /// </summary>
        internal static string MsjProc5 {
            get {
                return ResourceManager.GetString("MsjProc5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SMACOP Versión 2.0.
        /// </summary>
        internal static string Titulo {
            get {
                return ResourceManager.GetString("Titulo", resourceCulture);
            }
        }
    }
}
