//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace smacop2
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class logicopEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto logicopEntities usando la cadena de conexión encontrada en la sección 'logicopEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public logicopEntities() : base("name=logicopEntities", "logicopEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto logicopEntities.
        /// </summary>
        public logicopEntities(string connectionString) : base(connectionString, "logicopEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto logicopEntities.
        /// </summary>
        public logicopEntities(EntityConnection connection) : base(connection, "logicopEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<lstentradasmat> lstentradasmats
        {
            get
            {
                if ((_lstentradasmats == null))
                {
                    _lstentradasmats = base.CreateObjectSet<lstentradasmat>("lstentradasmats");
                }
                return _lstentradasmats;
            }
        }
        private ObjectSet<lstentradasmat> _lstentradasmats;

        #endregion
        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet lstentradasmats. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTolstentradasmats(lstentradasmat lstentradasmat)
        {
            base.AddObject("lstentradasmats", lstentradasmat);
        }

        #endregion
    }
    

    #endregion
    
    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="logicopModel", Name="lstentradasmat")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class lstentradasmat : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto lstentradasmat.
        /// </summary>
        /// <param name="anul">Valor inicial de la propiedad anul.</param>
        /// <param name="cosm">Valor inicial de la propiedad cosm.</param>
        /// <param name="equ">Valor inicial de la propiedad equ.</param>
        /// <param name="fech">Valor inicial de la propiedad fech.</param>
        /// <param name="flem">Valor inicial de la propiedad flem.</param>
        /// <param name="mat">Valor inicial de la propiedad mat.</param>
        /// <param name="matfle">Valor inicial de la propiedad matfle.</param>
        /// <param name="nrec">Valor inicial de la propiedad nrec.</param>
        /// <param name="nsis">Valor inicial de la propiedad nsis.</param>
        /// <param name="ope">Valor inicial de la propiedad ope.</param>
        /// <param name="prov">Valor inicial de la propiedad prov.</param>
        /// <param name="rkm">Valor inicial de la propiedad rkm.</param>
        /// <param name="tifkm">Valor inicial de la propiedad tifkm.</param>
        /// <param name="timat">Valor inicial de la propiedad timat.</param>
        /// <param name="ttra">Valor inicial de la propiedad ttra.</param>
        /// <param name="volm">Valor inicial de la propiedad volm.</param>
        public static lstentradasmat Createlstentradasmat(global::System.Boolean anul, global::System.Decimal cosm, global::System.String equ, global::System.DateTime fech, global::System.Decimal flem, global::System.String mat, global::System.Decimal matfle, global::System.String nrec, global::System.String nsis, global::System.String ope, global::System.String prov, global::System.Decimal rkm, global::System.Decimal tifkm, global::System.Decimal timat, global::System.String ttra, global::System.Decimal volm)
        {
            lstentradasmat lstentradasmat = new lstentradasmat();
            lstentradasmat.anul = anul;
            lstentradasmat.cosm = cosm;
            lstentradasmat.equ = equ;
            lstentradasmat.fech = fech;
            lstentradasmat.flem = flem;
            lstentradasmat.mat = mat;
            lstentradasmat.matfle = matfle;
            lstentradasmat.nrec = nrec;
            lstentradasmat.nsis = nsis;
            lstentradasmat.ope = ope;
            lstentradasmat.prov = prov;
            lstentradasmat.rkm = rkm;
            lstentradasmat.tifkm = tifkm;
            lstentradasmat.timat = timat;
            lstentradasmat.ttra = ttra;
            lstentradasmat.volm = volm;
            return lstentradasmat;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean anul
        {
            get
            {
                return _anul;
            }
            set
            {
                if (_anul != value)
                {
                    OnanulChanging(value);
                    ReportPropertyChanging("anul");
                    _anul = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("anul");
                    OnanulChanged();
                }
            }
        }
        private global::System.Boolean _anul;
        partial void OnanulChanging(global::System.Boolean value);
        partial void OnanulChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal cosm
        {
            get
            {
                return _cosm;
            }
            set
            {
                if (_cosm != value)
                {
                    OncosmChanging(value);
                    ReportPropertyChanging("cosm");
                    _cosm = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("cosm");
                    OncosmChanged();
                }
            }
        }
        private global::System.Decimal _cosm;
        partial void OncosmChanging(global::System.Decimal value);
        partial void OncosmChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String equ
        {
            get
            {
                return _equ;
            }
            set
            {
                if (_equ != value)
                {
                    OnequChanging(value);
                    ReportPropertyChanging("equ");
                    _equ = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("equ");
                    OnequChanged();
                }
            }
        }
        private global::System.String _equ;
        partial void OnequChanging(global::System.String value);
        partial void OnequChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fech
        {
            get
            {
                return _fech;
            }
            set
            {
                if (_fech != value)
                {
                    OnfechChanging(value);
                    ReportPropertyChanging("fech");
                    _fech = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("fech");
                    OnfechChanged();
                }
            }
        }
        private global::System.DateTime _fech;
        partial void OnfechChanging(global::System.DateTime value);
        partial void OnfechChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal flem
        {
            get
            {
                return _flem;
            }
            set
            {
                if (_flem != value)
                {
                    OnflemChanging(value);
                    ReportPropertyChanging("flem");
                    _flem = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("flem");
                    OnflemChanged();
                }
            }
        }
        private global::System.Decimal _flem;
        partial void OnflemChanging(global::System.Decimal value);
        partial void OnflemChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String mat
        {
            get
            {
                return _mat;
            }
            set
            {
                if (_mat != value)
                {
                    OnmatChanging(value);
                    ReportPropertyChanging("mat");
                    _mat = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("mat");
                    OnmatChanged();
                }
            }
        }
        private global::System.String _mat;
        partial void OnmatChanging(global::System.String value);
        partial void OnmatChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal matfle
        {
            get
            {
                return _matfle;
            }
            set
            {
                if (_matfle != value)
                {
                    OnmatfleChanging(value);
                    ReportPropertyChanging("matfle");
                    _matfle = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("matfle");
                    OnmatfleChanged();
                }
            }
        }
        private global::System.Decimal _matfle;
        partial void OnmatfleChanging(global::System.Decimal value);
        partial void OnmatfleChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nrec
        {
            get
            {
                return _nrec;
            }
            set
            {
                if (_nrec != value)
                {
                    OnnrecChanging(value);
                    ReportPropertyChanging("nrec");
                    _nrec = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("nrec");
                    OnnrecChanged();
                }
            }
        }
        private global::System.String _nrec;
        partial void OnnrecChanging(global::System.String value);
        partial void OnnrecChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nsis
        {
            get
            {
                return _nsis;
            }
            set
            {
                if (_nsis != value)
                {
                    OnnsisChanging(value);
                    ReportPropertyChanging("nsis");
                    _nsis = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("nsis");
                    OnnsisChanged();
                }
            }
        }
        private global::System.String _nsis;
        partial void OnnsisChanging(global::System.String value);
        partial void OnnsisChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ope
        {
            get
            {
                return _ope;
            }
            set
            {
                if (_ope != value)
                {
                    OnopeChanging(value);
                    ReportPropertyChanging("ope");
                    _ope = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ope");
                    OnopeChanged();
                }
            }
        }
        private global::System.String _ope;
        partial void OnopeChanging(global::System.String value);
        partial void OnopeChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String prov
        {
            get
            {
                return _prov;
            }
            set
            {
                if (_prov != value)
                {
                    OnprovChanging(value);
                    ReportPropertyChanging("prov");
                    _prov = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("prov");
                    OnprovChanged();
                }
            }
        }
        private global::System.String _prov;
        partial void OnprovChanging(global::System.String value);
        partial void OnprovChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal rkm
        {
            get
            {
                return _rkm;
            }
            set
            {
                if (_rkm != value)
                {
                    OnrkmChanging(value);
                    ReportPropertyChanging("rkm");
                    _rkm = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("rkm");
                    OnrkmChanged();
                }
            }
        }
        private global::System.Decimal _rkm;
        partial void OnrkmChanging(global::System.Decimal value);
        partial void OnrkmChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal tifkm
        {
            get
            {
                return _tifkm;
            }
            set
            {
                if (_tifkm != value)
                {
                    OntifkmChanging(value);
                    ReportPropertyChanging("tifkm");
                    _tifkm = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("tifkm");
                    OntifkmChanged();
                }
            }
        }
        private global::System.Decimal _tifkm;
        partial void OntifkmChanging(global::System.Decimal value);
        partial void OntifkmChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal timat
        {
            get
            {
                return _timat;
            }
            set
            {
                if (_timat != value)
                {
                    OntimatChanging(value);
                    ReportPropertyChanging("timat");
                    _timat = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("timat");
                    OntimatChanged();
                }
            }
        }
        private global::System.Decimal _timat;
        partial void OntimatChanging(global::System.Decimal value);
        partial void OntimatChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ttra
        {
            get
            {
                return _ttra;
            }
            set
            {
                if (_ttra != value)
                {
                    OnttraChanging(value);
                    ReportPropertyChanging("ttra");
                    _ttra = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ttra");
                    OnttraChanged();
                }
            }
        }
        private global::System.String _ttra;
        partial void OnttraChanging(global::System.String value);
        partial void OnttraChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal volm
        {
            get
            {
                return _volm;
            }
            set
            {
                if (_volm != value)
                {
                    OnvolmChanging(value);
                    ReportPropertyChanging("volm");
                    _volm = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("volm");
                    OnvolmChanged();
                }
            }
        }
        private global::System.Decimal _volm;
        partial void OnvolmChanging(global::System.Decimal value);
        partial void OnvolmChanged();

        #endregion
    
    }

    #endregion
    
}
